/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ExposedFixedPointInterface extends ethers.utils.Interface {
  functions: {
    "calculateMantissa(uint256,uint256)": FunctionFragment;
    "divideUintByMantissa(uint256,uint256)": FunctionFragment;
    "multiplyUintByMantissa(uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "calculateMantissa",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "divideUintByMantissa",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "multiplyUintByMantissa",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateMantissa",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "divideUintByMantissa",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multiplyUintByMantissa",
    data: BytesLike
  ): Result;

  events: {};
}

export class ExposedFixedPoint extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ExposedFixedPointInterface;

  functions: {
    calculateMantissa(
      numerator: BigNumberish,
      denominator: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "calculateMantissa(uint256,uint256)"(
      numerator: BigNumberish,
      denominator: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    divideUintByMantissa(
      dividend: BigNumberish,
      mantissa: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "divideUintByMantissa(uint256,uint256)"(
      dividend: BigNumberish,
      mantissa: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    multiplyUintByMantissa(
      b: BigNumberish,
      mantissa: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "multiplyUintByMantissa(uint256,uint256)"(
      b: BigNumberish,
      mantissa: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  calculateMantissa(
    numerator: BigNumberish,
    denominator: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "calculateMantissa(uint256,uint256)"(
    numerator: BigNumberish,
    denominator: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  divideUintByMantissa(
    dividend: BigNumberish,
    mantissa: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "divideUintByMantissa(uint256,uint256)"(
    dividend: BigNumberish,
    mantissa: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  multiplyUintByMantissa(
    b: BigNumberish,
    mantissa: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "multiplyUintByMantissa(uint256,uint256)"(
    b: BigNumberish,
    mantissa: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    calculateMantissa(
      numerator: BigNumberish,
      denominator: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calculateMantissa(uint256,uint256)"(
      numerator: BigNumberish,
      denominator: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    divideUintByMantissa(
      dividend: BigNumberish,
      mantissa: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "divideUintByMantissa(uint256,uint256)"(
      dividend: BigNumberish,
      mantissa: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    multiplyUintByMantissa(
      b: BigNumberish,
      mantissa: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "multiplyUintByMantissa(uint256,uint256)"(
      b: BigNumberish,
      mantissa: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    calculateMantissa(
      numerator: BigNumberish,
      denominator: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calculateMantissa(uint256,uint256)"(
      numerator: BigNumberish,
      denominator: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    divideUintByMantissa(
      dividend: BigNumberish,
      mantissa: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "divideUintByMantissa(uint256,uint256)"(
      dividend: BigNumberish,
      mantissa: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    multiplyUintByMantissa(
      b: BigNumberish,
      mantissa: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "multiplyUintByMantissa(uint256,uint256)"(
      b: BigNumberish,
      mantissa: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    calculateMantissa(
      numerator: BigNumberish,
      denominator: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "calculateMantissa(uint256,uint256)"(
      numerator: BigNumberish,
      denominator: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    divideUintByMantissa(
      dividend: BigNumberish,
      mantissa: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "divideUintByMantissa(uint256,uint256)"(
      dividend: BigNumberish,
      mantissa: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    multiplyUintByMantissa(
      b: BigNumberish,
      mantissa: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "multiplyUintByMantissa(uint256,uint256)"(
      b: BigNumberish,
      mantissa: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
