/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ProxyFactoryInterface extends ethers.utils.Interface {
  functions: {
    "c_0x2b4df744(bytes32)": FunctionFragment;
    "deployMinimal(address,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "c_0x2b4df744",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deployMinimal",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "c_0x2b4df744",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployMinimal",
    data: BytesLike
  ): Result;

  events: {
    "ProxyCreated(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ProxyCreated"): EventFragment;
}

export class ProxyFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ProxyFactoryInterface;

  functions: {
    c_0x2b4df744(
      c__0x2b4df744: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "c_0x2b4df744(bytes32)"(
      c__0x2b4df744: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    deployMinimal(
      _logic: string,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "deployMinimal(address,bytes)"(
      _logic: string,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  c_0x2b4df744(
    c__0x2b4df744: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  "c_0x2b4df744(bytes32)"(
    c__0x2b4df744: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  deployMinimal(
    _logic: string,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "deployMinimal(address,bytes)"(
    _logic: string,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    c_0x2b4df744(
      c__0x2b4df744: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "c_0x2b4df744(bytes32)"(
      c__0x2b4df744: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    deployMinimal(
      _logic: string,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "deployMinimal(address,bytes)"(
      _logic: string,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    ProxyCreated(proxy: null): TypedEventFilter<[string], { proxy: string }>;
  };

  estimateGas: {
    c_0x2b4df744(
      c__0x2b4df744: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "c_0x2b4df744(bytes32)"(
      c__0x2b4df744: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deployMinimal(
      _logic: string,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "deployMinimal(address,bytes)"(
      _logic: string,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    c_0x2b4df744(
      c__0x2b4df744: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "c_0x2b4df744(bytes32)"(
      c__0x2b4df744: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deployMinimal(
      _logic: string,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "deployMinimal(address,bytes)"(
      _logic: string,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
