/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { ExposedFixedPoint } from "../ExposedFixedPoint";

export class ExposedFixedPoint__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<ExposedFixedPoint> {
    return super.deploy(overrides || {}) as Promise<ExposedFixedPoint>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ExposedFixedPoint {
    return super.attach(address) as ExposedFixedPoint;
  }
  connect(signer: Signer): ExposedFixedPoint__factory {
    return super.connect(signer) as ExposedFixedPoint__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ExposedFixedPoint {
    return new Contract(address, _abi, signerOrProvider) as ExposedFixedPoint;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "numerator",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "denominator",
        type: "uint256",
      },
    ],
    name: "calculateMantissa",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "dividend",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "mantissa",
        type: "uint256",
      },
    ],
    name: "divideUintByMantissa",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "mantissa",
        type: "uint256",
      },
    ],
    name: "multiplyUintByMantissa",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610389806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806340200d20146100465780639cde940514610092578063a94b7334146100de575b600080fd5b61007c6004803603604081101561005c57600080fd5b81019080803590602001909291908035906020019092919050505061012a565b6040518082815260200191505060405180910390f35b6100c8600480360360408110156100a857600080fd5b81019080803590602001909291908035906020019092919050505061013e565b6040518082815260200191505060405180910390f35b610114600480360360408110156100f457600080fd5b810190808035906020019092919080359060200190929190505050610152565b6040518082815260200191505060405180910390f35b60006101368383610166565b905092915050565b600061014a83836101a5565b905092915050565b600061015e83836101e4565b905092915050565b60008061017c848461022390919063ffffffff16565b9050610199670de0b6b3a7640000826102a990919063ffffffff16565b90508091505092915050565b6000806101c384670de0b6b3a764000061022390919063ffffffff16565b90506101d883826102a990919063ffffffff16565b90508091505092915050565b600080610202670de0b6b3a76400008561022390919063ffffffff16565b905061021783826102a990919063ffffffff16565b90508091505092915050565b60008083141561023657600090506102a3565b600082840290508284828161024757fe5b041461029e576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260218152602001806103336021913960400191505060405180910390fd5b809150505b92915050565b6000808211610320576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252601a8152602001807f536166654d6174683a206469766973696f6e206279207a65726f00000000000081525060200191505060405180910390fd5b81838161032957fe5b0490509291505056fe536166654d6174683a206d756c7469706c69636174696f6e206f766572666c6f77a26469706673582212201361648c62092b6bd698e8446e7447842a1bae6a957aee8d099913f41a47597164736f6c634300060c0033";
