/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IReserve } from "../IReserve";

export class IReserve__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IReserve {
    return new Contract(address, _abi, signerOrProvider) as IReserve;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "yieldSource",
        type: "address",
      },
    ],
    name: "reserveRateMantissa",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "yieldSource",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "withdrawReserve",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
